spring:
  application:
    name: kb-mood-diary
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID:}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET:kb-mood-diary-default-secret-key-256-bit}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

app:
  upload:
    path: ${UPLOAD_PATH:./uploads}
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:80}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mariadb://localhost:3306/kb_mood_diary?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USER:kb_user}
    password: ${DB_PASSWORD:kb_password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

logging:
  level:
    com.nodove.MoodDiary: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:kb_mood_diary}?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USER:kb_user}
    password: ${DB_PASSWORD:kb_password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

logging:
  level:
    com.nodove.MoodDiary: INFO
    org.springframework.security: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
  
  datasource:
    url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:kb_mood_diary}?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USER:kb_user}
    password: ${DB_PASSWORD:kb_password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

logging:
  level:
    com.nodove.MoodDiary: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:mood_diary}
    username: ${DB_USER:mood_user}
    password: ${DB_PASSWORD:mood_password}
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}